#!/usr/bin/env python3
"""Write codex/AGENTS.md: CLAUDE.md with its imported files written in place.

Codex reads ~/.codex/AGENTS.md and follows no import lines. CLAUDE.md pulls
in CLAUDE_CODING.md and CLAUDE_WRITING_STANCE.md with lines that begin with
"@", which Claude Code expands and Codex reads as bare paths. This script
expands them the same way, so the file Codex reads says what the file Claude
Code reads says. Nothing is reworded: Jake asked for the two to stay alike so
that he is never unsure which rules a session has.

The @ lines carry absolute paths from one laptop. The build resolves each by
its basename under the repository root, so a clone anywhere produces the same
file.

    python3 scripts/build_agents_md.py            # write codex/AGENTS.md
    python3 scripts/build_agents_md.py --check    # exit 1 if it is stale

Codex reads at most project_doc_max_bytes of instructions, 32 KiB by default,
and truncates the rest without saying so. The merged file is above that, so
the build warns and names the setting.
"""

import argparse
import os
import re
import sys

IMPORT_LINE = re.compile(r"^@(\S+)\s*$")
CODEX_DEFAULT_BUDGET = 32768
OUTPUT = os.path.join("codex", "AGENTS.md")

HEADER = """<!-- Generated by scripts/build_agents_md.py from CLAUDE.md. Do not edit
     this file; edit CLAUDE.md and run `make agents-md`. It is CLAUDE.md with
     the two files CLAUDE.md imports written out in place, because Codex reads
     one AGENTS.md and follows no import lines. Where the text says "Claude
     Code," read Codex. The skills it names are linked into ~/.codex/skills
     and are invoked as $name. -->

"""


class MissingImport(Exception):
    """CLAUDE.md imports a file that is not in the repository."""


class NonAscii(Exception):
    """A source file breaks the ASCII-only rule. The build stops rather than
    carry the character into a file the rule says must not have one."""


def read_ascii(path):
    with open(path, "rb") as fh:
        data = fh.read()
    for offset, byte in enumerate(data):
        if byte > 126:
            line = data[:offset].count(b"\n") + 1
            raise NonAscii("%s line %d has a byte outside printable ASCII; the "
                           "rule in CLAUDE.md forbids it" % (os.path.basename(path), line))
    return data.decode("ascii")


def build(repo):
    """Return the text of codex/AGENTS.md for the repository at `repo`."""
    lines = read_ascii(os.path.join(repo, "CLAUDE.md")).splitlines(keepends=True)

    out = [HEADER]
    for line in lines:
        match = IMPORT_LINE.match(line)
        if match is None:
            out.append(line)
            continue
        name = os.path.basename(match.group(1))
        path = os.path.join(repo, name)
        if not os.path.isfile(path):
            raise MissingImport(
                "CLAUDE.md imports %s, and %s is not in the repository"
                % (match.group(1), name))
        body = read_ascii(path)
        if not body.endswith("\n"):
            body += "\n"
        # The markers say where the imported text starts and ends, so a reader
        # of the built file can tell which of the three sources a rule is in.
        out.append("<!-- Begin %s, imported by CLAUDE.md with an @ line. -->\n\n" % name)
        out.append(body)
        out.append("\n<!-- End %s -->\n" % name)
    return "".join(out)


def output_path(repo):
    return os.path.join(repo, OUTPUT)


def write(repo):
    """Build and write codex/AGENTS.md. Returns the path written."""
    path = output_path(repo)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="ascii") as fh:
        fh.write(build(repo))
    return path


def check(repo):
    """True when the tracked file equals a fresh build."""
    path = output_path(repo)
    if not os.path.isfile(path):
        return False
    with open(path, encoding="ascii") as fh:
        return fh.read() == build(repo)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repo", default=os.path.dirname(os.path.dirname(
        os.path.abspath(__file__))))
    ap.add_argument("--check", action="store_true",
                    help="report whether codex/AGENTS.md is current; change nothing")
    args = ap.parse_args(argv)

    if args.check:
        if check(args.repo):
            print("%s is current." % OUTPUT)
            return 0
        print("%s is behind CLAUDE.md or a file it imports; run `make agents-md`."
              % OUTPUT)
        return 1

    path = write(args.repo)
    size = os.path.getsize(path)
    print("wrote %s (%d bytes)" % (OUTPUT, size))
    if size > CODEX_DEFAULT_BUDGET:
        print("warning: %s is %d bytes, above Codex's default "
              "project_doc_max_bytes of %d; set project_doc_max_bytes = 65536 "
              "in ~/.codex/config.toml or Codex truncates it silently."
              % (OUTPUT, size, CODEX_DEFAULT_BUDGET), file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
